# theme used
remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs

title: RAPIDS Docs
description: RAPIDS demo, process, and technical documentation.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://docs.rapids.ai"

permalink: pretty
exclude:
  - CONTRIBUTING.md
  - README.md
  - release_checklist.md
  - customization/
  - update_symlinks.sh
  - _config_ignore_api.yml
  - api/
include:
  - _sources
  - _static
  - _images

collections:
  notices:
    output: true

aux_links:
  "View Docs on GitHub":
    - "https://github.com/rapidsai/docs"

social:
  google-groups:
    name: Google Groups
    url: https://groups.google.com/forum/#!forum/rapidsai
    fa-icon-class: fas fa-users
  twitter:
    name: Twitter
    username: rapidsai
    url: https://twitter.com/rapidsai
    fa-icon-class: fab fa-twitter
  slack:
    name: Slack
    url: https://join.slack.com/t/rapids-goai/shared_invite/zt-h54mq1uv-KHeHDVCYs8xvZO5AB~ctTQ
    fa-icon-class: fab fa-slack
  stack-overflow:
    name: Stack Overflow
    url: https://stackoverflow.com/tags/rapids
    fa-icon-class: fab fa-stack-overflow

plugins:
  - jekyll-redirect-from

# Enable or disable the site search
search_enabled: true

