# theme used
remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs

title: RAPIDS Docs
description: RAPIDS demo, process, and technical documentation.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://docs.rapids.ai"

permalink: pretty
exclude:
  - CONTRIBUTING.md
  - README.md
  - release_checklist.md
  - ci/
  - node_modules/
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - .ruff_cache/
include:
  - _sources
  - _static
  - _images
  - _redirects
  - _sphinx_javascript_frameworks_compat.js

collections:
  notices:
    output: true

aux_links:
  "View Docs on GitHub":
    - "https://github.com/rapidsai/docs"

nav_external_links:
  - title: Deployment Guides
    url: /deployment/stable/

social:
  twitter:
    name: Twitter
    username: rapidsai
    url: https://twitter.com/rapidsai
    fa-icon-class: fab fa-twitter
  slack:
    name: Slack
    url: https://rapids.ai/slack-invite
    fa-icon-class: fab fa-slack
  stack-overflow:
    name: Stack Overflow
    url: https://stackoverflow.com/tags/rapids
    fa-icon-class: fab fa-stack-overflow

# Enable or disable the site search
search_enabled: true
